# permissions for end users to view btservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: btserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: torrent-operator
    app.kubernetes.io/part-of: torrent-operator
    app.kubernetes.io/managed-by: kustomize
  name: btserver-viewer-role
rules:
- apiGroups:
  - torrent.alphayax.com
  resources:
  - btservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - torrent.alphayax.com
  resources:
  - btservers/status
  verbs:
  - get
