# permissions for end users to edit qbittorrentservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: qbittorrentserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: torrent-operator
    app.kubernetes.io/part-of: torrent-operator
    app.kubernetes.io/managed-by: kustomize
  name: qbittorrentserver-editor-role
rules:
- apiGroups:
  - torrent.alphayax.com
  resources:
  - qbittorrentservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torrent.alphayax.com
  resources:
  - qbittorrentservers/status
  verbs:
  - get
