---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - torrent.alphayax.com
  resources:
  - qbittorrentservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torrent.alphayax.com
  resources:
  - qbittorrentservers/finalizers
  verbs:
  - update
- apiGroups:
  - torrent.alphayax.com
  resources:
  - qbittorrentservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - torrent.alphayax.com
  resources:
  - torrents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torrent.alphayax.com
  resources:
  - torrents/finalizers
  verbs:
  - update
- apiGroups:
  - torrent.alphayax.com
  resources:
  - torrents/status
  verbs:
  - get
  - patch
  - update
