apiVersion: torrent.alphayax.com/v1alpha1
kind: BtServer
metadata:
  labels:
    app.kubernetes.io/name: btserver
    app.kubernetes.io/instance: btserver-sample
    app.kubernetes.io/part-of: torrent-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: torrent-operator
  name: qbittorrent
spec:
  serverUri: "https://qbittorent"
  type: qBittorrent
  credentials:
    #username: ""
    #password: ""
    usernameFromSecret:
      key: qbt-user
      name: bt-creds
      namespace: tools
    passwordFromSecret:
      key: qbt-pass
      name: bt-creds
      namespace: tools
