//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BtServer) DeepCopyInto(out *BtServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BtServer.
func (in *BtServer) DeepCopy() *BtServer {
	if in == nil {
		return nil
	}
	out := new(BtServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BtServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BtServerList) DeepCopyInto(out *BtServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BtServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BtServerList.
func (in *BtServerList) DeepCopy() *BtServerList {
	if in == nil {
		return nil
	}
	out := new(BtServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BtServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BtServerSpec) DeepCopyInto(out *BtServerSpec) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BtServerSpec.
func (in *BtServerSpec) DeepCopy() *BtServerSpec {
	if in == nil {
		return nil
	}
	out := new(BtServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BtServerSpecCredentials) DeepCopyInto(out *BtServerSpecCredentials) {
	*out = *in
	out.PasswordFromSecret = in.PasswordFromSecret
	out.UsernameFromSecret = in.UsernameFromSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BtServerSpecCredentials.
func (in *BtServerSpecCredentials) DeepCopy() *BtServerSpecCredentials {
	if in == nil {
		return nil
	}
	out := new(BtServerSpecCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BtServerStatus) DeepCopyInto(out *BtServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BtServerStatus.
func (in *BtServerStatus) DeepCopy() *BtServerStatus {
	if in == nil {
		return nil
	}
	out := new(BtServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemFromSecret) DeepCopyInto(out *ItemFromSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemFromSecret.
func (in *ItemFromSecret) DeepCopy() *ItemFromSecret {
	if in == nil {
		return nil
	}
	out := new(ItemFromSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerRef) DeepCopyInto(out *ServerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerRef.
func (in *ServerRef) DeepCopy() *ServerRef {
	if in == nil {
		return nil
	}
	out := new(ServerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Torrent) DeepCopyInto(out *Torrent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Torrent.
func (in *Torrent) DeepCopy() *Torrent {
	if in == nil {
		return nil
	}
	out := new(Torrent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Torrent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentList) DeepCopyInto(out *TorrentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Torrent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentList.
func (in *TorrentList) DeepCopy() *TorrentList {
	if in == nil {
		return nil
	}
	out := new(TorrentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorrentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentSpec) DeepCopyInto(out *TorrentSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentSpec.
func (in *TorrentSpec) DeepCopy() *TorrentSpec {
	if in == nil {
		return nil
	}
	out := new(TorrentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentStatus) DeepCopyInto(out *TorrentStatus) {
	*out = *in
	out.Speed = in.Speed
	out.Peers = in.Peers
	out.Data = in.Data
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentStatus.
func (in *TorrentStatus) DeepCopy() *TorrentStatus {
	if in == nil {
		return nil
	}
	out := new(TorrentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentStatusData) DeepCopyInto(out *TorrentStatusData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentStatusData.
func (in *TorrentStatusData) DeepCopy() *TorrentStatusData {
	if in == nil {
		return nil
	}
	out := new(TorrentStatusData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentStatusPeers) DeepCopyInto(out *TorrentStatusPeers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentStatusPeers.
func (in *TorrentStatusPeers) DeepCopy() *TorrentStatusPeers {
	if in == nil {
		return nil
	}
	out := new(TorrentStatusPeers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentStatusSpeed) DeepCopyInto(out *TorrentStatusSpeed) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentStatusSpeed.
func (in *TorrentStatusSpeed) DeepCopy() *TorrentStatusSpeed {
	if in == nil {
		return nil
	}
	out := new(TorrentStatusSpeed)
	in.DeepCopyInto(out)
	return out
}
